const Sdata = [
  {
    id: "1",
    title: "Paneer Biryani",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/paneer-biryani-recipe-500x500.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "2",
    title: "Paneer Tikka",
    img: "https://i.ytimg.com/vi/7pz2mhyGjC8/maxresdefault.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "3",
    title: "Paneer Biryani",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/paneer-biryani-recipe-500x500.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "4",
    title: "Paneer Tikka",
    img: "https://i.ytimg.com/vi/7pz2mhyGjC8/maxresdefault.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "5",
    title: "Paneer Biryani",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/paneer-biryani-recipe-500x500.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "6",
    title: "Paneer Tikka",
    img: "https://i.ytimg.com/vi/7pz2mhyGjC8/maxresdefault.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "7",
    title: "Paneer Biryani",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/paneer-biryani-recipe-500x500.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "8",
    title: "Paneer Tikka",
    img: "https://i.ytimg.com/vi/7pz2mhyGjC8/maxresdefault.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "9",
    title: "Paneer Biryani",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/paneer-biryani-recipe-500x500.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "10",
    title: "Paneer Tikka",
    img: "https://i.ytimg.com/vi/7pz2mhyGjC8/maxresdefault.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "11",
    title: "Paneer Biryani",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/paneer-biryani-recipe-500x500.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "12",
    title: "Paneer Tikka",
    img: "https://i.ytimg.com/vi/7pz2mhyGjC8/maxresdefault.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "13",
    title: "Paneer Biryani",
    img: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/01/paneer-biryani-recipe-500x500.jpg",
    pdetails: "Best Food",
    price: "",
  },
  {
    id: "14",
    title: "Paneer Tikka",
    img: "https://i.ytimg.com/vi/7pz2mhyGjC8/maxresdefault.jpg",
    pdetails: "Best Food",
    price: "",
  },
];
export default Sdata;
